DEFAULT_PORT = 8111
DEFAULT_SOURCE = 'paques-python-client'
DEFAULT_AUTH = None  # type: Optional[Any]
DEFAULT_MAX_ATTEMPTS = 3
DEFAULT_REQUEST_TIMEOUT = 30.0  # type: float

HTTP = 'http'
HTTPS = 'https'

# URL_STATEMENT_PATH = '/v1/statement'
URL_STATEMENT_PATH = ''

HEADER_PREFIX = 'X-Paques-'

HEADER_SOURCE = HEADER_PREFIX + 'Source'
HEADER_USER = HEADER_PREFIX + 'User'

HEADER_SESSION = HEADER_PREFIX + 'Session'
HEADER_SET_SESSION = HEADER_PREFIX + 'Set-Session'
HEADER_CLEAR_SESSION = HEADER_PREFIX + 'Clear-Session'

HEADER_STARTED_TRANSACTION = HEADER_PREFIX + 'Started-Transaction-Id'
# HEADER_TRANSACTION = HEADER_PREFIX + 'Transaction-Id
